services:
  frontend:
    image: giobels/simlady-stock:latest
    container_name: simlady-stock-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: "http://backend:8000"
      NEXT_PUBLIC_PDF_API_URL: "http://ia:30000"
      SERPAPI_API_KEY: ${SERPAPI_API_KEY}
      JWT_SECRET: ${JWT_SECRET}

  backend:
    image: giobels/simlady-backend:latest
    container_name: simlady-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_RABBITMQ_HOST: ${SPRING_RABBITMQ_HOST}
      SPRING_RABBITMQ_PORT: ${SPRING_RABBITMQ_PORT}
      SPRING_RABBITMQ_USERNAME: ${SPRING_RABBITMQ_USERNAME}
      SPRING_RABBITMQ_PASSWORD: ${SPRING_RABBITMQ_PASSWORD}
      POSTGRESQL_URL: "jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?user=${DB_USER}&password=${DB_PASSWORD}"
      POSTGRESQL_USERNAME: ${DB_USER}
      POSTGRESQL_PASSWORD: ${DB_PASSWORD}
      SYSADMIN_USER: ${SYSADMIN_USER}
      SYSADMIN_EMAIL: ${SYSADMIN_EMAIL}
      SYSADMIN_PASSWORD: ${SYSADMIN_PASSWORD}
    depends_on:
      rabbitmq:
        condition: service_healthy

  ia:
    image: giobels/simlady-pypdf:latest
    container_name: simlady-ia
    restart: unless-stopped
    ports:
      - "30000:30000"
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

  postgres17:
    image: postgres:17
    container_name: postgres17
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - pg-network

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${SPRING_RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${SPRING_RABBITMQ_PASSWORD}
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 10s
      retries: 10

  bot:
    image: giobels/simlady-bot:latest
    container_name: simlady-bot
    restart: unless-stopped
    ports:
      - "8084:8084"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_RABBITMQ_HOST: ${SPRING_RABBITMQ_HOST}
      SPRING_RABBITMQ_PORT: ${SPRING_RABBITMQ_PORT}
      SPRING_RABBITMQ_USERNAME: ${SPRING_RABBITMQ_USERNAME}
      SPRING_RABBITMQ_PASSWORD: ${SPRING_RABBITMQ_PASSWORD}
      BOT_TOKEN: ${BOT_TOKEN}

networks:
  pg-network:
    driver: bridge
